FROM wootechspace/grafana-k6:0.4.2

# USER root

# RUN set -eux && \
#     apt-get update && apt-get install -y --no-install-recommends --no-install-suggests \
#     curl \
#     dnsutils \
#     procps \
#     net-tools && \
#     apt-get autoremove -y && \
#     rm -rf /tmp/* /var/tmp/* /var/cache/apt/* /var/lib/apt/lists/*

ENTRYPOINT ["/bin/bash"]